import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import FavoriteCell from '../components/favorite-cell'
import { favorites, socials } from '../utils/constants'
import SocialButton from '../components/social-button'
import Wrapper from '../components/wrapper'
import { useHubspotForm } from '@aaronhayes/react-use-hubspot-form'

const Home: NextPage = () => {
  const { loaded, formCreated } = useHubspotForm({
    portalId: '9081438',
    formId: '6d925ffc-28b9-43a2-8bf8-ce41753ddc48',
    target: '#hs-form',
  })

  return (
    <div>
      <Head>
        <title>Tyler Shukert</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <header>
        <div className="h-screen flex justify-center items-center bg-header bg-cover bg-fixed bg-center px-6">
          <h1 className="text-white px-12 py-6 border-4 border-white text-4xl md:text-8xl">
            Hi, I&apos;m Tyler
          </h1>
        </div>
      </header>
      <main>
        <Wrapper>
          <div className="md:grid ,d:grid-cols-2 md:grid-rows-3">
            <h2 className="text-center pb-4 text-3xl md:text-5xl md:col-start-2 md:col-end-3 md:pb-0">
              About Me
            </h2>
            <img
              className="profile-image w-44 mx-auto md:col-start-1 md:col-end-2 md:row-start-1 md:row-end-4"
              src="images/profile.jpg"
              alt="profile"
            />
            <p className="pt-4 text-lg md:col-start-2 md:col-end-3 md:row-start-2 md:row-end-3 md:pt-0 md:pb-4">
              Mobile/ Web app developer. <br />
              Currently working as a solutions engineer at HubSpot. <br />
              Enjoy playing team handball. <br />
            </p>
            <div className="flex justify-center md:col-start-2 md:col-end-3 md:row-start-3 md:row-end-4">
              {socials.map((social) => {
                return <SocialButton key={social.name} social={social}></SocialButton>
              })}
            </div>
          </div>
        </Wrapper>
        <div className="bg-fun bg-center bg-fixed bg-cover">
          <Wrapper>
            <h2 className="text-white text-center pb-5 text-3xl md:text-5xl">Things I enjoy</h2>
            <div className="flex justify-center items-center flex-wrap">
              {favorites.map((favorite) => {
                return <FavoriteCell key={favorite.title} favorite={favorite}></FavoriteCell>
              })}
            </div>
          </Wrapper>
        </div>

        <Wrapper>
          <h2 className="text-center pb-5 text-3xl md:text-5xl">Contact me</h2>
          <div id="hs-form"></div>
          {loaded && formCreated ? null : (
            <div className="text-center py-8 text-lg">Loading Form...</div>
          )}
        </Wrapper>
      </main>
    </div>
  )
}

export default Home
